### ISSUE TITLE
Caidas del bot

### ISSUE THREAD

**Issue by pagoru** [darkaqua/darkbot#13]
El bot se cae en algunos momentos y se vuelve a levantar, pero hay algunos puntos que se desconecta.

Log:
```
Here we go! ❤
-Port: 7777
-Last versión: 0.2
-Current versión: 0.3
2313243 se ha unido al servidor! :)
ShadowBlade se ha unido al servidor! :)
Ultrafer50 se ha unido al servidor! :)
Here we go! ❤
-Port: 7777
-Last versión: 0.2
-Current versión: 0.3
Here we go! ❤
-Port: 7777
-Last versión: 0.2
-Current versión: 0.3
NayasMcBlack se ha unido al servidor! :)
Here we go! ❤
-Port: 7777
-Last versión: 0.2
-Current versión: 0.3
11000matias se ha unido al servidor! :)
```

**Comment by MagicInventor** [comment]
Debe ser la implementación de la API de discord en node. Esto suele pasar por la falta de actividad en los web sockets, si todo el rato estaría reciviendo paquetes (se supone que tiene que estar el famoso"ping y pong" para que esto no pase), nunca se desconectaría.

Supongo que sera eso, por experiencia, hace unos meses me paso cuando estuve haciendo el bot twitch (después termine haciendo un cliente irc para hacer spam já).

Recomendaría que vieran lo que pasa desde wireshark y revisar un poco el código de la implementación de la API.
https://github.com/hydrabolt/discord.js/tree/master/src/client/websocket
