### ISSUE TITLE
El comando !help no funciona.

### ISSUE THREAD

**Issue by mcmacker4** [darkaqua/darkbot#20]
El comando `!help` de @MagicInventor da error:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Bad Request`.

**Comment by MagicInventor** [comment]
Que raro, la última vez que lo testee funcionaba
![alt text](https://puu.sh/sZ7W7.png)

**Comment by MagicInventor** [comment]
![alt text](https://puu.sh/sZ97y.png)
Ya lo solucione
https://github.com/darkaqua/darkbot/pull/23
