### ISSUE TITLE
!status para cambiar el status del bot

### ISSUE THREAD

**Issue by pagoru** [darkaqua/darkbot#30]

**Comment by MagicInventor** [comment]
Con estado, ¿a qué te refieres? ¿si esta offline o online? ¿o a los juegos?

![alt text](https://puu.sh/t2Yzd.png "Logo Title Text 1")

**Comment by mcmacker4** [comment]
Se refiere a `Online`, `Idle`, `Do Not Disturb` y `Invisible`, que viene a ser el color de la bolita en la foto de perfil. Para cambiar el juego se usaria `!game`.

**Comment by mcmacker4** [comment]
Y ahora que lo pienso, mejor no hacer el comando `!game` porque el juego esta reservado para visualizar la version en la que se encuentra el bot.
