### ISSUE TITLE
Automatizar los cambios (webhooks)

### ISSUE THREAD

**Issue by mcmacker4** [darkaqua/darkbot#6]
Usando webhooks se puede automatizar lo de aplicar los cambios de la branch master al bot. Quiere decir que si alguien cambia la master, github hace un post request al servidor donde se esta ejecutando el bot, y hay un servidor hecho con node escuchando. Entonces el servidor de node, para el bot, descarga los cambios y vuelve a ejecutar el nuevo bot, totalmente automatico.

**Comment by pagoru** [comment]
```JS
const http = require('http')
const createHandler = require('github-webhook-handler')
const handler = createHandler({ path: '/webhook', secret: 'myhashsecret' })

http.createServer(function (req, res) {
    handler(req, res, function (err) {
        res.statusCode = 202;
        res.end('no such location');

        const event = req.headers['x-github-event'];

        if(event == "release"){
            console.log("new release");
        }
    });
}).listen(7777);
```
